# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=64, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='task begin time')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='task end time')),
            ],
        ),
    ]
